// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzVxtsKI8ct5NKxt9nJxHD9yhE4s-VCNs',
    appId: '1:1039920263383:web:2e8bbd86ad4c0b341e0092',
    messagingSenderId: '1039920263383',
    projectId: 'food-recipe-app-ce709',
    authDomain: 'food-recipe-app-ce709.firebaseapp.com',
    storageBucket: 'food-recipe-app-ce709.firebasestorage.com',
    measurementId: 'G-ZY45Z3BGKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG7M5-0_w7RVNDLrVO7Jgu_lD-FalPKGA',
    appId: '1:1039920263383:android:18f837efea74f9691e0092',
    messagingSenderId: '1039920263383',
    projectId: 'food-recipe-app-ce709',
    storageBucket: 'food-recipe-app-ce709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26ExKvF9SL50R24ntuwcg3XWxN2_qkTc',
    appId: '1:1039920263383:ios:87144ffc284c6a241e0092',
    messagingSenderId: '1039920263383',
    projectId: 'food-recipe-app-ce709',
    storageBucket: 'food-recipe-app-ce709.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD26ExKvF9SL50R24ntuwcg3XWxN2_qkTc',
    appId: '1:1039920263383:ios:87144ffc284c6a241e0092',
    messagingSenderId: '1039920263383',
    projectId: 'food-recipe-app-ce709',
    storageBucket: 'food-recipe-app-ce709.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzVxtsKI8ct5NKxt9nJxHD9yhE4s-VCNs',
    appId: '1:1039920263383:web:c410d4d48a35130f1e0092',
    messagingSenderId: '1039920263383',
    projectId: 'food-recipe-app-ce709',
    authDomain: 'food-recipe-app-ce709.firebaseapp.com',
    storageBucket: 'food-recipe-app-ce709.firebasestorage.app',
    measurementId: 'G-KTY42R2KG5',
  );
}
